version: '3.8'

services:
  team-status:
    build: .
    container_name: team-manager-app
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - SESSION_SECRET=baconpostei